### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Saiks** [rsummers618/HTPC_Alexa_Skill#7]
@rsummers618 have a question if i may... In the demo you have netflix working, I can't seem to find any repo that works. Can you point me to the right direction. Also you you using the Eminence skin? It seems less cluttered and if not which one. Thx again

**Comment by bcliang** [comment]
If you are based off of [0.0.4](https://github.com/rsummers618/HTPC_Alexa_Skill/tree/e2f86998dd5beae47d4e444eb54895bb01a291f0)

There was a bug in how the script was launching chrome (unless you were on android). To fix, make a modification to **service.py** to comment out lines 178, 180, and 181:
`#    if  xbmc.getCondVisibility("system.platform.android"):`
`stringparam = 'http://netflix.com/watch/' + netflixid`
`#    else:`
`#        stringparam = '?kiosk=yes&mode=showSite&stopPlayback=yes&url=http://netflix.com/watch/'+netflixid`

Essentially, the extra request parameters should not be sent to launch_chrome() since that function handles adding those parameters as well. The result was an incorrect url being sent to chrome.

**Comment by Saiks** [comment]
I'm on version 0.1.0 I can't seem to find a working version of chrome launcher for Netflix to work. Each time it launches, its me a chrome launcher error.Can anyone direct me to one.

**Comment by rsummers618** [comment]
Can you post the log of the chrome launcher error along with your system specs? (Kodi version, os Version, etc.)

**Comment by Saiks** [comment]
http://pastebin.com/PURsfVqT
http://pastebin.com/A5SE2mQ0

**Comment by rsummers618** [comment]
This is an issue with chrome launcher, not with the Alexa skill. 

Chrome launcher is getting "permission denied"  when trying to launch your chrome executable. 

Make sure you have chrome (or chromium)  installed and reachable in the directory checked  by chrome launcher for Linux. 

Also make sure the binary has the proper permissions

**Comment by Saiks** [comment]
I have chromium install.. I think my problem is in chrome launcher settings which uses a custom chrome script/path which I can't seem to figure where to point it to. Is there an option to use it without the script. Also if i uncheck the script box it result to chrome not found.

**Comment by Saiks** [comment]
I finally found a version of chrome launcher that actually work which was the culpit. Who would have tho there were sooo many. Anyways thanks all
